apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-app
type: Opaque
stringData:
  db_user: "django_user"
  db_password: "SuperSecret123!"
  secret_key: "django-insecure-your-secret-key-here"
